create table tb_author (id bigserial not null, name varchar(255), primary key (id));
create table tb_character (id bigserial not null, name varchar(255), primary key (id));
create table tb_comic (price float4, id bigint not null, description varchar(3000), isbn varchar(255), title varchar(255), primary key (id));
create table tb_comic_author (author_id bigint not null, comic_id bigint not null, primary key (author_id, comic_id));
create table tb_comic_character (character_id bigint not null, comic_id bigint not null, primary key (character_id, comic_id));
create table tb_comment (date timestamp(6), id bigserial not null, review_id bigint, user_id bigint, content varchar(3000), title varchar(255), primary key (id));
create table tb_like (liked boolean, review_id bigint not null, user_id bigint not null, primary key (review_id, user_id));
create table tb_profiles (profiles integer, user_id bigint not null);
create table tb_rate (rate integer, comic_id bigint not null, user_id bigint not null, primary key (comic_id, user_id));
create table tb_reading (favourit boolean, reading boolean, comic_id bigint not null, user_id bigint not null, primary key (comic_id, user_id));
create table tb_review (comic_id bigint, date timestamp(6), id bigserial not null, user_id bigint, content varchar(3000), title varchar(255), primary key (id));
create table tb_user (birth_date date, id bigserial not null, email varchar(255), name varchar(255), password varchar(255), phone varchar(255), primary key (id));
alter table if exists tb_comic_author add constraint FKepokr0xrsipvlvrb5u3539jc5 foreign key (author_id) references tb_author;
alter table if exists tb_comic_author add constraint FKgd4tdhlp3k1o3c1d4tc19pd7k foreign key (comic_id) references tb_comic;
alter table if exists tb_comic_character add constraint FKtqqvpd11lolfipaapcaxoywjg foreign key (character_id) references tb_character;
alter table if exists tb_comic_character add constraint FK643mxvjkylu82xtw8iod2tiai foreign key (comic_id) references tb_comic;
alter table if exists tb_comment add constraint FKask1mkng79rj0hb2icpujaby2 foreign key (review_id) references tb_review;
alter table if exists tb_comment add constraint FK45c1cuqlljd60ihc9j0962ekq foreign key (user_id) references tb_user;
alter table if exists tb_like add constraint FK5imkcido53o1iyxnxxdty6fcs foreign key (review_id) references tb_review;
alter table if exists tb_like add constraint FK245qh9w9lju2652at7qisf9rt foreign key (user_id) references tb_user;
alter table if exists tb_profiles add constraint FKpxga1m62fbs2evtwrvvjs2jnq foreign key (user_id) references tb_user;
alter table if exists tb_rate add constraint FKqpr8a6vmqdy25uook95df6jvh foreign key (comic_id) references tb_comic;
alter table if exists tb_rate add constraint FKfbf1dm3vuj91omd9yfnfa9j6 foreign key (user_id) references tb_user;
alter table if exists tb_reading add constraint FK55bmvj7wtankayepcgjo4wqok foreign key (comic_id) references tb_comic;
alter table if exists tb_reading add constraint FK62xop0cihvcwya6vpc6jss60m foreign key (user_id) references tb_user;
alter table if exists tb_review add constraint FKhu33r4fpmv2b1j3cawcjnr5pd foreign key (comic_id) references tb_comic;
alter table if exists tb_review add constraint FKqeh83gbufxg1ft0ubwn7w0tty foreign key (user_id) references tb_user;
create table tb_author (id bigserial not null, name varchar(255), primary key (id));
create table tb_character (id bigserial not null, name varchar(255), primary key (id));
create table tb_comic (price float4, id bigint not null, description varchar(3000), isbn varchar(255), title varchar(255), primary key (id));
create table tb_comic_author (author_id bigint not null, comic_id bigint not null, primary key (author_id, comic_id));
create table tb_comic_character (character_id bigint not null, comic_id bigint not null, primary key (character_id, comic_id));
create table tb_comment (date timestamp(6), id bigserial not null, review_id bigint, user_id bigint, content varchar(3000), title varchar(255), primary key (id));
create table tb_like (liked boolean, review_id bigint not null, user_id bigint not null, primary key (review_id, user_id));
create table tb_profiles (profiles integer, user_id bigint not null);
create table tb_rate (rate integer, comic_id bigint not null, user_id bigint not null, primary key (comic_id, user_id));
create table tb_reading (favourit boolean, reading boolean, comic_id bigint not null, user_id bigint not null, primary key (comic_id, user_id));
create table tb_review (comic_id bigint, date timestamp(6), id bigserial not null, user_id bigint, content varchar(3000), title varchar(255), primary key (id));
create table tb_user (birth_date date, id bigserial not null, email varchar(255), name varchar(255), password varchar(255), phone varchar(255), primary key (id));
alter table if exists tb_comic_author add constraint FKepokr0xrsipvlvrb5u3539jc5 foreign key (author_id) references tb_author;
alter table if exists tb_comic_author add constraint FKgd4tdhlp3k1o3c1d4tc19pd7k foreign key (comic_id) references tb_comic;
alter table if exists tb_comic_character add constraint FKtqqvpd11lolfipaapcaxoywjg foreign key (character_id) references tb_character;
alter table if exists tb_comic_character add constraint FK643mxvjkylu82xtw8iod2tiai foreign key (comic_id) references tb_comic;
alter table if exists tb_comment add constraint FKask1mkng79rj0hb2icpujaby2 foreign key (review_id) references tb_review;
alter table if exists tb_comment add constraint FK45c1cuqlljd60ihc9j0962ekq foreign key (user_id) references tb_user;
alter table if exists tb_like add constraint FK5imkcido53o1iyxnxxdty6fcs foreign key (review_id) references tb_review;
alter table if exists tb_like add constraint FK245qh9w9lju2652at7qisf9rt foreign key (user_id) references tb_user;
alter table if exists tb_profiles add constraint FKpxga1m62fbs2evtwrvvjs2jnq foreign key (user_id) references tb_user;
alter table if exists tb_rate add constraint FKqpr8a6vmqdy25uook95df6jvh foreign key (comic_id) references tb_comic;
alter table if exists tb_rate add constraint FKfbf1dm3vuj91omd9yfnfa9j6 foreign key (user_id) references tb_user;
alter table if exists tb_reading add constraint FK55bmvj7wtankayepcgjo4wqok foreign key (comic_id) references tb_comic;
alter table if exists tb_reading add constraint FK62xop0cihvcwya6vpc6jss60m foreign key (user_id) references tb_user;
alter table if exists tb_review add constraint FKhu33r4fpmv2b1j3cawcjnr5pd foreign key (comic_id) references tb_comic;
alter table if exists tb_review add constraint FKqeh83gbufxg1ft0ubwn7w0tty foreign key (user_id) references tb_user;
